Add an auto mode in switch-screen, remove screen-hotplug

diff --git a/screen/switch-screen b/screen/switch-screen
--- a/screen/switch-screen
+++ b/screen/switch-screen
@@ -25,25 +25,50 @@ _list_screens() {
   }' | column -t
 }
 
-_usage() {
+_auto_biggest() {
+  selection=$(_list_screens | awk '{ split($2,d,"x"); print d[1]*d[2]" "$1" "$3 }' | sort -nr | head -n1)
+  if ! grep -q ON <<<$selection; then
+    _main -p $(cut -d' ' -f2 <<<$selection)
+  fi
+}
+
+_auto() {
+  local policy="$1"
+  case "$policy" in
+    biggest) _auto_biggest;;
+    *)       echo "Invalid policy \"$policy\".";;
+  esac
+  exit
+}
+
+_cli_error() {
+  echo "Type \"$CMDNAME --help\" to see usage." >&2
+  exit 1
+}
+
+_help() {
   echo "This command is a wrapper around xrandr to simplify screen management.
 
 Usage:
   switch-screen -L
   switch-screen [-d] [--dry-run] -p SCREEN0 [-l SCREEN1] [-r ...]
+  switch-screen -A biggest
 
 Options:
   -L  --list     List screens
+  -A  --auto     Turn on/off screen with a defined policy
 
   -p  --primary  Select the first screen (mandatory)
   -l  --left     Select the screen on the left
   -t  --top      Select the screen on the top
   -b  --bottom   Select the screen on the bottom
   -r  --right    Select the screen on the right
+
+  -h  --help     Print this help message
   -d  --debug    Enable debuging messages
       --dry-run  Print the xrandr command and exit
 
-Exemples:
+Examples:
   switch-screen -L                   List all screens connected
   switch-screen -p hdmi-1            Use HDMI-1 screen and turn off all others screens
   switch-screen -p hdmi-1 -l lvds-1  Use HDMI-1 as a main screen and put LVDS-1 as a
@@ -52,12 +77,12 @@ Exemples:
 }
 
 _main() {
-  SHORT=dLp:t:l:b:r:
-  LONG=debug,list,dry-run,primary:,top:,left:,bottom:,right:
+  SHORT=hdLp:t:l:b:r:A:
+  LONG=help,debug,list,dry-run,primary:,top:,left:,bottom:,right:,auto:
 
   # Print usage when no options are set
   if [[ $# == 0 ]]; then
-    _usage
+    _cli_error
   fi
 
   # - Temporarily store output to be able to check for errors
@@ -66,17 +91,23 @@ _main() {
   PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$CMDNAME" -- "$@")
   if [[ $? != 0 ]]; then
     echo
-    _usage
+    _cli_error
     exit 2
   fi
   # use eval with "$PARSED" to properly handle the quoting
   eval set -- "$PARSED"
+
+  local auto
 
   # now enjoy the options in order and nicely split until we see --
   while true; do
     case "$1" in
       -d|--debug)
         debug=y
+        shift
+        ;;
+      -h|--help)
+        _help
         shift
         ;;
       --dry-run)
@@ -86,6 +117,10 @@ _main() {
       -L|--list)
         list=y
         shift
+        ;;
+      -A|--auto)
+        auto="$2"
+        shift 2
         ;;
       -p|--primary)
         primary_screen="$2"
@@ -112,7 +147,8 @@ _main() {
         break
         ;;
       *)
-        _usage
+        cli_error
+        break
         ;;
       esac
   done
@@ -120,6 +156,10 @@ _main() {
   if [[ "$list" == "y" ]]; then
     _list_screens
     exit
+  fi
+
+  if [[ -n "$auto" ]]; then
+    _auto "$auto"
   fi
 
   # If we select --primary so we want change screen layout
